# Generated by Django 4.0.5 on 2022-06-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
