# Generated by Django 4.0.5 on 2022-06-12 08:33

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('accounts', '0002_customuser_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='time',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
